const List<String> emotionalWords = [
  'happiness', 'joy', 'love', 'sadness', 'anger', 'fear', 'hope', 'grief',
  'depression', 'anxiety', 'excitement', 'frustration', 'contentment',
  'stress', 'self-esteem', 'empathy', 'resentment', 'guilt', 'pride',
  'shame', 'anger management', 'joyfulness', 'sorrow', 'calmness',
  'enthusiasm', 'loneliness', 'harmony', 'discomfort', 'gratefulness',
  'confidence', 'appreciation', 'boredom', 'exasperation', 'serenity',
  'despair', 'nervousness', 'passion', 'euphoria', 'fearfulness',
  'hopefulness', 'insecurity', 'warmth', 'compassion', 'self-compassion',
  'anger issues', 'caring', 'tenderness', 'distress', 'satisfaction',
  'melancholy', 'optimism', 'pessimism', 'exhilaration', 'joyous',
  'vulnerability', 'doubt', 'frustrating', 'cheerfulness', 'unease',
  'concern', 'embarrassment', 'nervousness', 'calm', 'overwhelm',
  'cheer', 'anger issues', 'pleasure', 'content', 'displeasure',
  'comfort', 'sad', 'stressful', 'courage', 'confidence issues',
  'motivation', 'angst', 'jubilation', 'eager', 'dejected',
  'satisfying', 'moodiness', 'serenity', 'elation', 'bitterness',
  'despondency', 'upset', 'vigor', 'delight', 'trouble',
  'uplifted', 'joyful', 'tranquility', 'affection', 'irritation',
  'loveable', 'emotionally drained', 'discontent', 'emotional support',
  'prideful', 'dismay', 'tension', 'happiness', 'agitation',
  'heartfelt', 'sensitive', 'joyous', 'self-assurance', 'regret',
  'frustrating', 'emotionally overwhelmed', 'sympathy', 'thrill',
  'exasperated', 'relief', 'fury', 'enthusiastic', 'feeling overwhelmed',
  'compassionate', 'sorrowful', 'pleasant', 'joyfulness', 'angry',
  'hopeful', 'numbness', 'emotional state', 'sadness', 'ecstasy',
  'mournful', 'gaiety', 'desperation', 'positive', 'negative',
  'irritated', 'elation', 'serene', 'cheerful', 'warm-hearted',
  'discomforting', 'intense', 'melancholy', 'delighted', 'dismal',
  'optimistic', 'grateful', 'happiness', 'contented', 'joyful',
  'angry', 'gloomy', 'uplifted', 'distressing', 'cheerful',
  'happy', 'bored', 'disheartened', 'well-being', 'uplifting',
  'empathy', 'grief-stricken', 'happy-go-lucky', 'serene', 'sorrowful',
  'contentment', 'emotionally stable', 'angry', 'sadness', 'delight',
  'vulnerable', 'cheer', 'joy', 'mood', 'comforting',
  'supportive', 'pleased', 'desolate', 'melancholic', 'energetic',
  'confident', 'optimistic', 'emotionally charged', 'joyful', 'mournful',
  'positive', 'frustration', 'content', 'despairing', 'prideful',
  'relaxed', 'happy', 'cheerful', 'dismay', 'sorrowful',
  'disheartened', 'encouraged', 'uplifted', 'contentment', 'worried',
  'serene', 'unhappy', 'positive', 'grief', 'sad', 'overjoyed',
  'emotionally stable', 'disturbed', 'uneasy', 'joy', 'pleased',
  'frustration', 'contented', 'fear', 'joyful', 'calm',
  'happy', 'stressed', 'emotionally upset', 'emotional state',
  'emotionally content', 'delighted', 'cheerfulness', 'joyful',
  'emotionally affected', 'anguish', 'serenity', 'heartwarming',
  'elated', 'supportive', 'dismayed', 'melancholy', 'elated',
  'gloomy', 'regretful', 'emotional distress', 'hopeful', 'confident',
  'pleasure', 'happiness', 'blissful', 'depressed', 'uplifting',
  'cheerful', 'emotionally drained', 'ecstatic', 'worried',
  'elation', 'gloom', 'positive', 'cheer', 'empathy',
  'resentful', 'joyous', 'distressing', 'dejected', 'pessimistic',
  'euphoric', 'angst', 'displeased', 'heartened', 'aggravated',
  'ecstatic', 'emotional burden', 'frustrated', 'heartache', 'mirth',
  'compassion', 'emotional upheaval', 'dismal', 'joyous', 'irate',
  'troubled', 'cheerfulness', 'gladness', 'resentment', 'overjoyed',
  'hopeless', 'angrily', 'raged', 'sadness', 'emotionally unsettled',
  'elation', 'happy', 'grief', 'emotionally tired', 'happy',
  'pleased', 'uplift', 'distress', 'hope', 'satisfaction',
  'joyful', 'elated', 'sorrow', 'emotionally drained', 'emotional stability',
  'troubled', 'satisfaction', 'contented', 'ecstasy', 'gloomy',
  'emotional burden', 'angrily', 'contented', 'joyful', 'grateful',
  'enthused', 'emotional fatigue', 'melancholic', 'upbeat', 'disheartened',
  'emotionally mixed', 'delightful', 'joy', 'resentful', 'pleased',
  'angrily', 'happy', 'pessimism', 'emotional upturn', 'contentment',
  'blessed', 'cheerfulness', 'gloom', 'cheer', 'emotionally disturbed',
  'uplifted', 'sorrowful', 'contentment', 'grief', 'calm',
  'dismay', 'happy', 'emotionally elated', 'distress', 'pleased',
  'contented', 'angry', 'melancholy', 'joy', 'pleased',
  'positive', 'depressed', 'satisfied', 'troubled', 'joyful',
  'frustration', 'elation', 'serene', 'anguish', 'pleased',
  'emotionally drained', 'gloom', 'elation', 'optimistic', 'pleased',
  'contentment', 'emotional upheaval', 'happy', 'troubled', 'joy',
  'upbeat', 'frustrated', 'serene', 'pleased', 'happy',
  'dismay', 'joyful', 'distressed', 'contented', 'happy',
  'elevated', 'calm', 'troubled', 'cheerful', 'uplifted',
  'happy', 'discontent', 'happy', 'joyful', 'pessimistic',
  'pleased', 'angry', 'contented', 'sorrowful', 'serene',
  'happiness', 'cheerful', 'happy', 'emotionally content', 'joyous',
  'depressed', 'cheerful', 'joy', 'pleased', 'contented',
  'discomfort', 'sadness', 'happy', 'pleased', 'joy',
  'emotionally relieved', 'satisfied', 'mood', 'happy', 'angry',
  'contented', 'serene', 'pleased', 'depressed', 'joyful',
  'happy', 'cheer', 'emotionally fulfilled', 'pleased', 'elation',
  'troubled', 'content', 'joyful', 'elated', 'melancholic',
  'serenity', 'uplifting', 'distressed', 'angry', 'happy',
  'pleased', 'optimistic', 'joyous', 'discomfort', 'cheerful',
  'contented', 'angry', 'happy', 'joy', 'pleased',
  'melancholy', 'emotional stress', 'joyous', 'gloomy', 'happy',
  'joy', 'emotionally disturbed', 'happy', 'pleased', 'uplifting',
  'distressed', 'elated', 'sad', 'contented', 'emotionally uplifted',
  'satisfied', 'angry', 'discomfort', 'happy', 'joyful',
  'cheerful', 'distress', 'happiness', 'elated', 'pleased',
  'happy', 'emotionally satisfied', 'joy', 'melancholic', 'angry',
  'sorrow', 'uplifting', 'happy', 'contented', 'distress',
  'satisfied', 'elation', 'happy', 'joyful', 'emotionally satisfied',
  'contented', 'sad', 'pleased', 'joyful', 'elation',
  'happy', 'emotional relief', 'cheerful', 'happy', 'melancholic',
  'joy', 'depressed', 'content', 'pleased', 'elation',
  'sadness', 'emotionally overwhelmed', 'happy', 'emotionally tired',
  'contented', 'joy', 'uplifting', 'cheer', 'happy',
  'sorrowful', 'contented', 'joyful', 'happy', 'pleased',
  'emotionally elated', 'angry', 'happy', 'distressed', 'pleased',
  'joy', 'contented', 'happy', 'uplifting', 'depressed',
  'satisfied', 'melancholic', 'joyful', 'contented', 'happy',
  'distress', 'emotionally disturbed', 'cheerful', 'happy', 'joyful',
  'emotionally content', 'happy', 'distressed', 'pleased', 'sadness',
  'elation', 'content', 'happy', 'joyful', 'cheerful',
  'emotionally drained', 'happiness', 'pleased', 'melancholic', 'happy',
  'elation', 'sadness', 'joy', 'happy', 'content',
  'emotionally upset', 'cheerful', 'happy', 'joyful', 'content',
  'distress', 'satisfied', 'elation', 'happy', 'joy',
  'emotional state', 'happy', 'contented', 'sad', 'pleased',
  'joyful', 'uplifting', 'happy', 'melancholic', 'cheerful',
  'happy', 'distress', 'joy', 'pleased', 'emotionally stable',
  'contented', 'happy', 'sadness', 'joyful', 'uplifting',
  'emotionally drained', 'happy', 'pleased', 'melancholy', 'joy',
  'elation', 'distressed', 'happy', 'contented', 'joy',
  'cheerful', 'depressed', 'happy', 'pleased', 'emotionally drained',
  'happy', 'joy', 'satisfaction', 'melancholic', 'contented',
  'pleased', 'happiness', 'joyful', 'emotionally content', 'cheerful',
  'sad', 'happy', 'joy', 'contented', 'cheerful',
  'emotionally satisfied', 'uplifting', 'happy', 'contented', 'sorrowful',
  'pleased', 'joyful', 'happy', 'contented', 'emotionally relieved',
  'distressed', 'happy', 'joy', 'contented', 'cheerful',
  'sad', 'emotionally drained', 'happy', 'joyful', 'contented',
  'happy', 'cheerful', 'elation', 'sadness', 'contented',
  'joy', 'happiness', 'cheerful', 'emotionally satisfied', 'happy',
  'sorrow', 'joyful', 'contented', 'happy', 'pleased',
  'emotionally drained', 'happy', 'cheerful', 'joy', 'contented',
  'distressed', 'sadness', 'happiness', 'joyful', 'pleased',
  'happy', 'emotionally content', 'cheerful', 'joy', 'satisfied',
  'melancholic', 'pleased', 'happy', 'joyful', 'contented',
  'cheerful', 'satisfied', 'happy', 'joy', 'distress',
  'emotionally disturbed', 'cheerful', 'joy', 'pleased', 'happy',
  'contented', 'happy', 'emotionally elated', 'joyful', 'sadness',
  'happy', 'pleased', 'contented', 'joy', 'emotionally relieved',
  'cheerful', 'joyful', 'satisfaction', 'happy', 'distressed',
  'contented', 'elation', 'happy', 'cheerful', 'sad',
  'emotionally overwhelmed', 'happy', 'cheerful', 'pleased', 'joy',
  'satisfaction', 'content', 'happy', 'emotionally stable', 'pleased',
  'joyful', 'sadness', 'happy', 'contented', 'cheerful',
  'elation', 'happy', 'joy', 'emotionally satisfied', 'sorrowful',
  'pleased', 'content', 'joyful', 'happy', 'cheerful',
  'emotionally satisfied', 'joy', 'happy', 'contented', 'pleased',
  'distress', 'happy', 'emotionally drained', 'joyful', 'satisfaction',
  'melancholic', 'contented', 'happy', 'pleased', 'joyful',
  'happy', 'sorrowful', 'elation', 'cheerful', 'distressed',
  'emotionally relieved', 'happy', 'joy', 'pleased', 'contented',
  'emotionally content', 'happy', 'distressed', 'joy', 'pleased',
  'happy', 'cheerful', 'joy', 'emotionally satisfied', 'melancholic',
  'content', 'happy', 'pleased', 'cheerful', 'distressed',
  'happy', 'joy', 'contented', 'emotionally drained', 'pleased',
  'happy', 'satisfaction', 'joyful', 'contented', 'cheerful',
  'emotionally relieved', 'sadness', 'happy', 'joy', 'pleased',
  'contented', 'cheerful', 'joyful', 'happy', 'emotionally satisfied',
  'distress', 'cheerful', 'happy', 'joy', 'contented',
  'emotionally drained', 'pleased', 'happy', 'sadness', 'joy',
  'happy', 'contented', 'cheerful', 'joyful', 'emotionally relieved',
  'pleased', 'distressed', 'happy', 'joy', 'contented',
  'emotionally content', 'happy', 'pleased', 'satisfaction', 'cheerful',
  'joyful', 'contented', 'happy', 'sadness', 'cheer',
  'emotionally fulfilled', 'happy', 'contented', 'pleased', 'joy',
  'emotionally relieved', 'joyful', 'happy', 'cheerful', 'contented',
  'sad', 'happy', 'pleased', 'joyful', 'distress',
  'emotionally satisfied', 'contented', 'happy', 'cheerful', 'sorrowful',
  'joy', 'happy', 'pleased', 'contented', 'emotionally stable',
  'joyful', 'pleased', 'cheerful', 'sad', 'happy',
  'contented', 'satisfaction', 'happy', 'emotionally relieved', 'cheerful',
  'joyful', 'happy', 'emotionally disturbed', 'contented', 'cheer',
  'happy', 'sorrowful', 'pleased', 'joy', 'distress',
  'emotionally relieved', 'happy', 'contented', 'cheerful', 'joyful',
  'emotionally fulfilled', 'sadness', 'happy', 'joy', 'pleased',
  'cheerful', 'happy', 'satisfied', 'contented', 'joyful',
  'emotionally drained', 'happy', 'cheerful', 'contented', 'sorrowful',
  'pleased', 'joy', 'emotionally stable', 'happy', 'contented',
  'cheerful', 'joyful', 'happy', 'satisfied', 'emotional relief',
  'contented', 'pleased', 'happy', 'joy', 'emotionally relieved',
  'satisfaction', 'cheerful', 'happy', 'contented', 'joy',
  'sadness', 'happy', 'emotionally drained', 'contented', 'joyful',
  'pleased', 'happy', 'emotionally satisfied', 'cheerful', 'content',
  'emotionally stable', 'happy', 'joy', 'pleased', 'cheerful',
  'satisfaction', 'happy', 'contented', 'emotionally relieved', 'joyful',
  'sad', 'happy', 'cheerful', 'contented', 'pleased',
  'happy', 'sorrowful', 'emotionally drained', 'joy', 'contented',
  'cheerful', 'happy', 'joyful', 'pleased', 'emotionally fulfilled',
  'content', 'happy', 'sadness', 'joy', 'cheerful',
  'emotionally relieved', 'happy', 'contented', 'pleased', 'joy',
  'satisfaction', 'happy', 'cheerful', 'joy', 'emotionally satisfied',
  'sad', 'happy', 'contented', 'pleased', 'joyful'
];

// Physical category words
const List<String> physicalWords = [
  'fitness', 'endurance', 'strength', 'stamina', 'agility', 'flexibility',
  'cardio', 'exercise', 'training', 'weightlifting', 'running', 'walking',
  'cycling', 'swimming', 'yoga', 'pilates', 'push-ups', 'sit-ups',
  'squats', 'jumping', 'stretching', 'cardiovascular', 'aerobic', 'power',
  'conditioning', 'athletics', 'bodybuilding', 'muscle', 'tone', 'balance',
  'speed', 'rehab', 'recovery', 'core', 'calisthenics', 'jump rope',
  'jogging', 'hiking', 'climbing', 'rowing', 'boxing', 'martial arts',
  'stretch', 'endurance training', 'push up', 'bodyweight', 'high-intensity',
  'sprint', 'warm-up', 'cool-down', 'strength training', 'muscle building',
  'aerobics', 'exercise routine', 'conditioning', 'fitness goal', 'body fat',
  'cardio workout', 'weight training', 'stretching routine', 'physical therapy',
  'personal best', 'crossfit', 'gym', 'workout', 'physical fitness', 'exercise',
  'high-impact', 'low-impact', 'body sculpting', 'body weight', 'endurance',
  'muscle tone', 'physical activity', 'body challenge', 'weight loss',
  'cardio exercise', 'athletic training', 'physical exercise', 'physical strength',
  'muscle endurance', 'sports', 'training program', 'physical stamina', 'core strength',
  'physical conditioning', 'performance', 'pushup challenge', 'run', 'sprint',
  'cycling challenge', 'swim', 'exercise challenge', 'resistance training', 'exercise plan',
  'core workout', 'strength challenge', 'fitness challenge', 'muscle gain', 'flexibility challenge',
  'athletic performance', 'agility training', 'physical challenge', 'reps', 'sets',
  'exercise session', 'fitness routine', 'powerlifting', 'physical exertion', 'cardio fitness',
  'endurance workout', 'strength program', 'muscle workout', 'weight loss program', 'strength goal',
  'running challenge', 'cycling workout', 'swimming challenge', 'gym workout', 'fitness goal',
  'endurance goal', 'physical strength training', 'conditioning workout', 'core exercise', 'stretching exercises',
  'muscle endurance workout', 'athletic goal', 'fitness program', 'resistance workout', 'cardio plan',
  'muscle training', 'body challenge', 'physical performance', 'exercise improvement', 'strength exercises',
  'cardio fitness challenge', 'physical workout', 'power challenge', 'endurance plan', 'physical strength goal',
  'high-intensity workout', 'low-impact exercise', 'muscle building program', 'physical goal', 'strengthening workout',
  'cardio challenge', 'fitness goal setting', 'muscle endurance challenge', 'core strength workout', 'physical activity challenge',
  'training plan', 'fitness improvement', 'muscle tone challenge', 'cardio workout plan', 'fitness test', 'performance goal',
  'exercise development', 'strength improvement', 'body conditioning', 'core strength challenge', 'endurance program',
  'strength and conditioning', 'physical health challenge', 'exercise improvement plan', 'muscle gain program', 'athletic challenge',
  'exercise routine challenge', 'endurance test', 'muscle performance', 'cardio routine', 'fitness improvement plan',
  'strength performance', 'muscle tone goal', 'cardio test', 'physical fitness goal', 'exercise program', 'performance improvement',
  'resistance challenge', 'fitness test challenge', 'physical exertion goal', 'strength improvement program', 'body training',
  'physical goal setting', 'muscle endurance goal', 'core fitness', 'high-intensity training', 'endurance development',
  'cardio fitness goal', 'muscle gain challenge', 'exercise performance', 'fitness progress', 'strength goal setting',
  'training challenge', 'cardio program', 'muscle endurance plan', 'physical test', 'exercise goals', 'performance plan',
  'strength development', 'endurance fitness', 'muscle conditioning', 'cardio improvement', 'fitness challenge plan',
  'physical health program', 'performance assessment', 'exercise challenge program', 'muscle tone program', 'fitness tracking',
  'training goal', 'muscle strength challenge', 'endurance workout plan', 'cardio exercises', 'physical challenge program',
  'fitness assessment', 'exercise improvement goal', 'resistance plan', 'strength test', 'cardio challenge plan',
  'muscle improvement', 'physical exercise plan', 'endurance challenge', 'fitness target', 'strength and fitness',
  'training progress', 'muscle workout plan', 'exercise development plan', 'core strength goal', 'cardio workout challenge',
  'muscle gain plan', 'physical improvement', 'exercise goal setting', 'performance improvement plan', 'fitness tracking plan',
  'endurance performance', 'muscle performance plan', 'cardio endurance', 'physical conditioning challenge', 'strength challenge plan',
  'fitness progress plan', 'exercise improvement strategy', 'muscle goal', 'endurance test challenge', 'fitness tracking challenge',
  'muscle workout program', 'cardio goal', 'physical strength performance', 'fitness challenge tracking', 'performance improvement goal',
  'exercise challenge assessment', 'strength training challenge', 'muscle gain assessment', 'endurance goal setting', 'cardio goal setting',
  'physical health improvement', 'muscle training goal', 'exercise performance plan', 'fitness target setting', 'cardio improvement plan',
  'strength performance goal', 'endurance fitness challenge', 'muscle conditioning program', 'training performance', 'cardio endurance challenge',
  'physical progress', 'fitness assessment plan', 'exercise goal tracking', 'muscle strength improvement', 'cardio training program',
  'fitness improvement tracking', 'performance development', 'exercise performance challenge', 'muscle gain tracking', 'endurance goal plan',
  'fitness performance assessment', 'muscle endurance program', 'physical challenge assessment', 'cardio improvement program', 'training goal setting',
  'endurance challenge tracking', 'muscle gain improvement', 'fitness development', 'cardio challenge strategy', 'exercise improvement tracking',
  'muscle strength goal setting', 'performance tracking', 'fitness assessment strategy', 'muscle conditioning tracking', 'physical health improvement plan',
  'cardio endurance assessment', 'strength and conditioning challenge', 'fitness progress tracking', 'endurance goal assessment', 'muscle improvement tracking',
  'cardio training challenge', 'performance improvement tracking', 'muscle conditioning assessment', 'physical challenge strategy', 'fitness challenge assessment',
  'endurance challenge strategy', 'muscle gain strategy', 'cardio fitness assessment', 'performance development plan', 'fitness tracking assessment',
  'muscle improvement strategy', 'physical health tracking', 'cardio performance goal', 'fitness strategy', 'exercise performance tracking',
  'muscle conditioning goal', 'performance progress', 'endurance improvement plan', 'fitness development plan', 'cardio endurance goal',
  'muscle gain performance', 'physical challenge goal', 'exercise challenge tracking', 'fitness performance goal', 'muscle improvement goal',
  'cardio challenge assessment', 'performance assessment plan', 'muscle conditioning strategy', 'physical health goal', 'fitness tracking strategy',
  'endurance performance tracking', 'cardio fitness goal', 'muscle gain strategy', 'performance improvement strategy', 'physical challenge tracking',
  'fitness goal assessment', 'muscle performance tracking', 'cardio challenge strategy', 'exercise improvement goal', 'performance tracking plan',
  'endurance challenge assessment', 'fitness development strategy', 'muscle gain improvement strategy', 'cardio performance assessment', 'physical health challenge',
  'fitness progress assessment', 'muscle performance goal', 'endurance tracking plan', 'cardio challenge performance', 'physical challenge improvement',
  'fitness goal tracking', 'muscle conditioning goal setting', 'performance development tracking', 'cardio improvement strategy', 'physical health improvement strategy',
  'muscle gain progress', 'fitness improvement strategy', 'cardio fitness tracking', 'performance challenge', 'muscle improvement plan',
  'endurance fitness strategy', 'physical challenge performance', 'fitness goal tracking plan', 'cardio endurance performance', 'muscle conditioning improvement',
  'performance strategy', 'fitness assessment tracking', 'cardio improvement goal', 'muscle conditioning assessment', 'physical health tracking strategy',
  'fitness progress goal', 'cardio performance improvement', 'muscle gain tracking strategy', 'performance assessment tracking', 'fitness challenge strategy',
  'endurance performance goal', 'cardio challenge improvement', 'muscle performance strategy', 'fitness development tracking', 'physical health goal setting',
  'muscle improvement strategy', 'performance challenge plan', 'cardio endurance tracking', 'physical challenge goal setting', 'fitness tracking improvement',
  'cardio fitness improvement', 'muscle gain assessment plan', 'performance improvement plan', 'fitness challenge performance', 'endurance goal strategy',
  'muscle conditioning development', 'physical health goal tracking', 'fitness assessment strategy', 'cardio performance tracking', 'endurance improvement assessment',
  'fitness challenge tracking plan', 'muscle gain improvement goal', 'performance tracking strategy', 'cardio fitness goal setting', 'physical challenge strategy'
  'fitness development tracking plan',
];

// Occupational category words
const List<String> occupationalWords = [
  'career', 'productivity', 'efficiency', 'professional', 'skills', 'development', 'growth',
  'leadership', 'management', 'teamwork', 'innovation', 'organization', 'strategy', 'planning',
  'project', 'deadline', 'performance', 'training', 'coaching', 'networking', 'promotion', 'collaboration',
  'communication', 'deadline', 'task', 'responsibility', 'goal', 'objectives', 'competency', 'workload',
  'time management', 'performance review', 'initiative', 'creativity', 'problem-solving', 'delegation',
  'workflow', 'career development', 'expertise', 'mentoring', 'achievement', 'work-life balance', 'training program',
  'skill development', 'job satisfaction', 'professional growth', 'project management', 'work efficiency', 'leadership skills',
  'employee engagement', 'team leadership', 'strategic planning', 'goal setting', 'career advancement', 'performance metrics',
  'productivity challenge', 'career goals', 'job performance', 'office productivity', 'professional development', 'project deadline',
  'business skills', 'collaborative work', 'strategic objectives', 'role expansion', 'career success', 'job effectiveness',
  'skill enhancement', 'professional training', 'leadership development', 'team collaboration', 'innovation challenge', 'task management',
  'organizational skills', 'goal achievement', 'project success', 'work improvement', 'team management', 'performance goals',
  'job skills', 'work objectives', 'professional challenge', 'efficiency improvement', 'career milestone', 'project efficiency',
  'time management skills', 'performance enhancement', 'workplace success', 'leadership challenge', 'skill acquisition', 'team development',
  'job growth', 'career progress', 'task completion', 'professional goals', 'office skills', 'work challenges', 'leadership achievements',
  'career development plan', 'project milestones', 'work productivity', 'management skills', 'training challenge', 'goal achievement plan',
  'workplace efficiency', 'career objectives', 'professional achievements', 'performance improvement', 'job satisfaction goals', 'team success',
  'strategic goals', 'workplace improvement', 'professional milestones', 'project management skills', 'leadership achievements', 'innovation in the workplace',
  'career progression', 'job efficiency', 'skill application', 'workforce development', 'team leadership skills', 'workplace challenge',
  'project deadlines', 'employee development', 'leadership progress', 'goal setting challenge', 'career growth opportunities', 'work productivity goals',
  'performance improvement plan', 'professional advancement', 'task achievement', 'project efficiency goals', 'workplace productivity', 'career enhancement',
  'leadership and management', 'professional skills', 'team collaboration skills', 'workplace strategy', 'project performance', 'career objectives',
  'efficiency goals', 'job performance metrics', 'career milestones', 'training and development', 'leadership and growth', 'project success metrics',
  'career success plan', 'workplace development', 'goal achievement strategies', 'performance enhancement plan', 'team performance', 'career success metrics',
  'workplace skills', 'professional effectiveness', 'job challenges', 'strategic goals setting', 'career development strategies', 'workplace performance',
  'management achievements', 'productivity improvements', 'leadership growth', 'skill development strategies', 'job performance goals', 'project goals',
  'work efficiency metrics', 'career progression goals', 'team success metrics', 'leadership performance', 'professional performance', 'task efficiency',
  'project management goals', 'workplace challenges', 'professional growth plan', 'leadership challenge plan', 'efficiency tracking', 'career growth plan',
  'workplace productivity metrics', 'task management strategies', 'performance goals setting', 'career advancement plan', 'skill acquisition plan', 'professional development metrics',
  'team performance goals', 'leadership effectiveness', 'project performance goals', 'work efficiency tracking', 'career advancement goals', 'team success plan',
  'professional effectiveness metrics', 'job performance tracking', 'workplace skill development', 'leadership development plan', 'performance metrics tracking', 'career growth strategies',
  'work efficiency improvement', 'team development strategies', 'job satisfaction improvement', 'leadership and productivity', 'career objectives plan', 'performance enhancement metrics',
  'workplace success strategies', 'professional success metrics', 'task management goals', 'leadership growth plan', 'career success tracking', 'efficiency improvement strategies',
  'team performance tracking', 'job skills development', 'project achievement metrics', 'professional progress plan', 'workplace performance goals', 'career milestones tracking',
  'leadership improvement plan', 'performance tracking strategies', 'workplace development plan', 'career progression tracking', 'job effectiveness goals', 'team success tracking',
  'project management improvement', 'career success assessment', 'performance goals tracking', 'leadership and efficiency', 'job performance enhancement', 'workplace challenge goals',
  'professional growth metrics', 'team productivity', 'work efficiency improvement plan', 'career development goals', 'leadership effectiveness metrics', 'project goals tracking',
  'performance improvement metrics', 'career growth assessment', 'workplace success plan', 'professional effectiveness tracking', 'task efficiency goals', 'team development goals',
  'leadership and growth metrics', 'job satisfaction metrics', 'career success plan', 'work efficiency strategies', 'performance assessment', 'professional advancement tracking',
  'team management plan', 'workplace productivity tracking', 'career advancement metrics', 'performance metrics assessment', 'leadership performance metrics', 'workplace effectiveness',
  'professional development goals', 'project efficiency metrics', 'task management plan', 'career progress metrics', 'leadership success plan', 'job performance improvement',
  'workplace challenge assessment', 'team performance improvement', 'career development tracking', 'professional growth strategies', 'performance improvement assessment', 'work efficiency metrics',
  'leadership goals', 'career achievement plan', 'task achievement metrics', 'workplace improvement plan', 'professional progress metrics', 'team success goals',
  'performance goals assessment', 'career progression metrics', 'leadership development goals', 'workplace performance metrics', 'job effectiveness assessment', 'professional development tracking',
  'career success metrics', 'work efficiency assessment', 'performance improvement plan', 'team productivity metrics', 'career growth tracking', 'professional effectiveness goals',
  'leadership improvement metrics', 'project performance assessment', 'workplace challenge plan', 'career development metrics', 'performance tracking plan', 'professional progress goals',
  'team success metrics', 'job performance goals', 'career growth plan', 'workplace productivity improvement', 'leadership and performance', 'task efficiency tracking',
  'project goals assessment', 'career success tracking metrics', 'workplace success metrics', 'performance development plan', 'professional growth tracking', 'team performance improvement plan',
  'leadership goals tracking', 'career advancement tracking', 'work efficiency improvement metrics', 'project achievement assessment', 'performance goals development', 'professional development plan',
  'career tracking metrics', 'workplace performance improvement', 'team success strategies', 'leadership effectiveness goals', 'job performance assessment metrics', 'career success development',
  'performance assessment metrics', 'work efficiency tracking plan', 'team productivity tracking', 'career progression strategies', 'project performance tracking', 'professional growth assessment',
  'workplace challenge tracking', 'career success evaluation', 'performance metrics development', 'leadership success metrics', 'job effectiveness improvement', 'team development tracking',
  'career development plan metrics', 'project efficiency tracking', 'workplace improvement metrics', 'professional growth evaluation', 'performance metrics tracking plan', 'career success tracking strategies',
  'leadership performance development', 'work efficiency goals setting', 'team success assessment', 'career advancement metrics tracking', 'project goals evaluation', 'performance development metrics',
  'professional effectiveness improvement', 'career progress evaluation', 'workplace success tracking', 'team performance development', 'leadership growth tracking', 'career success goals',
  'project management metrics', 'workplace productivity assessment', 'performance improvement tracking', 'job satisfaction evaluation', 'career tracking assessment', 'leadership improvement goals',
  'work efficiency assessment metrics', 'team productivity goals', 'career success plan metrics', 'performance tracking evaluation', 'professional development tracking metrics', 'career growth improvement',
  'leadership development metrics', 'workplace challenge evaluation', 'performance enhancement tracking', 'career success assessment plan', 'job performance metrics evaluation', 'team success metrics tracking',
  'project efficiency improvement', 'workplace productivity goals', 'career progression tracking metrics', 'professional growth assessment metrics', 'performance improvement strategy', 'leadership and effectiveness evaluation',
  'career development assessment', 'team performance tracking metrics', 'work efficiency development', 'project goals metrics', 'professional success metrics', 'performance evaluation metrics',
  'career success improvement plan', 'leadership performance goals', 'workplace challenge metrics', 'team productivity assessment', 'career advancement strategy', 'project performance evaluation',
  'professional growth tracking plan', 'performance metrics improvement', 'career growth assessment metrics', 'workplace success development', 'leadership goals evaluation', 'team success strategies',
  'project management goals tracking', 'career development tracking metrics', 'performance assessment tracking plan', 'professional effectiveness evaluation', 'work efficiency success metrics', 'team development strategies'
];

// Social category words
const List<String> socialWords = [
  'friendship', 'community', 'interaction', 'networking', 'relationships', 'communication', 'engagement',
  'socializing', 'connection', 'support', 'collaboration', 'group', 'teamwork', 'outreach', 'bonding',
  'event', 'gathering', 'party', 'dinner', 'meetup', 'network', 'social event', 'relationship-building',
  'conversation', 'networking event', 'social media', 'connection-building', 'engagement activities', 'support system',
  'group activity', 'community event', 'social interaction', 'shared experience', 'collaborative project', 'social engagement',
  'friend', 'social circle', 'team event', 'community outreach', 'peer support', 'interaction challenge', 'network building',
  'social challenge', 'relationship goals', 'social networking', 'event planning', 'group discussion', 'community involvement',
  'social connection', 'networking opportunities', 'collaborative effort', 'group project', 'social gathering', 'engagement challenge',
  'friendship-building', 'relationship development', 'community engagement', 'team collaboration', 'social support', 'connection goals',
  'social events', 'community support', 'relationship strengthening', 'networking activities', 'interaction goals', 'social improvement',
  'friendship goals', 'community involvement challenge', 'engagement strategies', 'networking challenge', 'group interaction', 'community events',
  'relationship enhancement', 'social activities', 'collaborative projects', 'social improvement plan', 'interaction activities', 'networking plan',
  'friendship development', 'community network', 'relationship challenge', 'social interaction goals', 'engagement plan', 'social circle',
  'team interaction', 'network building challenge', 'community project', 'friendship strategies', 'social outreach', 'group engagement',
  'community connections', 'social relationship goals', 'networking events', 'interaction plan', 'social bonding', 'collaborative activities',
  'relationship-building strategies', 'community networking', 'social circle expansion', 'engagement goals', 'networking improvement', 'friendship challenge',
  'community interaction', 'social relationship development', 'group networking', 'engagement strategies', 'social network building', 'friendship improvement',
  'relationship enhancement plan', 'community support challenge', 'interaction improvement', 'social network expansion', 'group collaboration', 'community connections challenge',
  'socializing plan', 'relationship development plan', 'networking improvement plan', 'community involvement strategies', 'engagement development', 'group interaction plan',
  'friendship and community', 'social challenge goals', 'networking opportunities challenge', 'relationship-building plan', 'social connection strategies', 'community interaction goals',
  'group engagement strategies', 'friendship and social networking', 'relationship development strategies', 'social improvement goals', 'engagement activities plan', 'networking goals',
  'community support strategies', 'social circle improvement', 'relationship-building activities', 'networking strategies', 'friendship and relationship development', 'group connection',
  'community engagement goals', 'interaction development', 'social events planning', 'networking plan strategies', 'engagement improvement plan', 'community network development',
  'friendship enhancement plan', 'socializing challenge', 'relationship-building goals', 'networking improvement goals', 'group socializing', 'community connection strategies',
  'social support challenge', 'interaction strategies', 'friendship improvement plan', 'relationship enhancement activities', 'community engagement planning', 'networking circle',
  'social event strategies', 'group networking challenge', 'engagement and interaction', 'community event planning', 'relationship-building activities plan', 'social connection goals',
  'networking and relationship development', 'friendship and community engagement', 'group connection strategies', 'social networking improvement', 'relationship development challenge', 'community involvement plan',
  'social support strategies', 'interaction and engagement', 'networking and community development', 'friendship and social challenges', 'relationship-building and networking', 'community support plan',
  'group socializing strategies', 'engagement and interaction challenge', 'social circle development', 'networking and social events', 'relationship enhancement strategies', 'community interaction plan',
  'friendship development strategies', 'networking and engagement goals', 'social connection development', 'relationship improvement goals', 'community and group interaction', 'social networking plan',
  'engagement and networking challenge', 'friendship and relationship goals', 'social events and activities', 'community support and development', 'interaction goals and strategies', 'networking circle development',
  'relationship-building and community', 'friendship and networking plan', 'social support and improvement', 'group interaction strategies', 'engagement and social challenges', 'community network planning',
  'relationship development and networking', 'social event improvement', 'community engagement strategies', 'networking and social connection', 'friendship challenge plan', 'interaction and networking goals',
  'social circle and community', 'relationship-building and support', 'engagement and social connection', 'community and networking', 'group engagement goals', 'friendship and social connection',
  'relationship improvement strategies', 'networking development plan', 'social support and goals', 'engagement planning', 'community interaction and support', 'social challenge development',
  'group networking strategies', 'relationship development and improvement', 'community and social events', 'engagement improvement goals', 'networking and friendship', 'social connection development plan',
  'relationship and community support', 'friendship enhancement strategies', 'social circle and engagement', 'networking and interaction goals', 'community event development', 'engagement and support',
  'relationship-building and challenge', 'social networking and events', 'community and interaction strategies', 'group connection and support', 'social development goals', 'friendship and community support',
  'networking improvement plan', 'engagement and social development', 'relationship enhancement goals', 'community interaction strategies', 'group networking and development', 'social support goals',
  'networking and community engagement', 'friendship and interaction goals', 'social connection and development', 'relationship development and support', 'engagement and community planning', 'networking goals and strategies',
  'community support and development plan', 'social event and networking', 'relationship-building and improvement', 'engagement strategies and goals', 'group socializing plan', 'friendship and social improvement',
  'community and relationship development', 'social support and networking', 'networking and event planning', 'interaction and support goals', 'engagement and community development', 'relationship and social goals',
  'friendship development and support', 'networking and interaction planning', 'social circle and goals', 'community event strategies', 'relationship improvement and development', 'engagement and social support',
  'group development and networking', 'friendship and engagement planning', 'community and social goals', 'relationship-building and community support', 'networking and social development', 'engagement strategies and planning',
  'social interaction goals and strategies', 'relationship development and community engagement', 'friendship improvement and development', 'group support and interaction', 'community and relationship support', 'engagement and networking goals',
  'social support and relationship development', 'networking and group interaction', 'friendship and social engagement planning', 'community development and networking', 'social connection and improvement plan', 'relationship and support strategies',
  'engagement and social support plan', 'group and community interaction', 'networking and social improvement', 'friendship and relationship development plan', 'community event and engagement', 'social development strategies',
  'relationship-building and support plan', 'group networking and development plan', 'engagement and community improvement', 'social connection and support', 'networking and relationship improvement', 'friendship and community development',
  'social event development strategies', 'community interaction goals and strategies', 'relationship development and improvement plan', 'engagement and networking development', 'group and social support strategies', 'friendship and social networking goals',
  'community and relationship goals', 'social support development plan', 'networking and event improvement', 'relationship and social support strategies', 'group interaction and engagement planning', 'community support and development goals',
  'engagement and friendship planning', 'social development and networking', 'relationship-building and goals', 'community and social improvement strategies', 'networking and engagement plan', 'friendship and relationship improvement goals',
  'social connection and goals', 'community and group support strategies', 'engagement and social connection plan', 'networking and relationship development', 'friendship and community improvement', 'social event and networking goals',
  'relationship and engagement planning', 'community support and networking development', 'group socializing and interaction goals', 'friendship and social connection plan', 'engagement and community goals', 'relationship-building and support strategies',
  'social networking development plan', 'community and relationship development goals', 'engagement and social improvement strategies', 'friendship and community support goals', 'networking and social goals', 'group and community interaction planning',
  'social support and engagement development', 'relationship and community support goals', 'networking and social improvement strategies', 'friendship and engagement goals', 'community and relationship goals development', 'engagement and networking improvement plan',
  'social connection and support goals', 'group and social development planning', 'community and relationship improvement plan', 'networking and social development goals', 'friendship and support strategies', 'engagement and social networking goals',
  'relationship-building and community goals', 'social support and development plan', 'networking and community goals development', 'friendship and social improvement plan', 'community and relationship development strategies', 'engagement and networking strategies',
  'social connection and improvement goals', 'group support and development'
];

// Spiritual category words
const List<String> spiritualWords = [
  'meditation', 'mindfulness', 'faith', 'enlightenment', 'soul', 'inner peace', 'prayer', 'self-discovery',
  'awareness', 'purpose', 'spirituality', 'reflection', 'awakening', 'tranquility', 'serenity', 'grace', 'rejuvenation',
  'balance', 'connection', 'higher self', 'compassion', 'forgiveness', 'growth', 'transcendence', 'sacred', 'manifestation',
  'contemplation', 'divinity', 'introspection', 'vibration', 'meditative state', 'inner journey', 'spiritual growth',
  'sacred space', 'soulful', 'surrender', 'sacred practice', 'soul-searching', 'sacred journey', 'inner light', 'sacred wisdom',
  'soulful connection', 'sacredness', 'spiritual path', 'inner healing', 'soul journey', 'inner strength', 'divine energy',
  'spiritual awakening', 'soulful exploration', 'enlightened self', 'sacred balance', 'spiritual practice', 'spiritual quest',
  'divine connection', 'sacred growth', 'spiritual insight', 'inner transformation', 'sacred purpose', 'divine guidance',
  'inner peace journey', 'spiritual balance', 'soulful healing', 'spiritual awareness', 'sacred self', 'inner wisdom',
  'divine purpose', 'spiritual insight', 'spiritual clarity', 'inner journey exploration', 'spiritual connection', 'spiritual development',
  'higher consciousness', 'spiritual self', 'sacred energy', 'inner peace quest', 'soulful journey', 'enlightened path',
  'spiritual unity', 'soulful balance', 'inner serenity', 'spiritual understanding', 'sacred healing', 'soulful quest',
  'spiritual harmony', 'inner peace practice', 'divine growth', 'sacred exploration', 'spiritual renewal', 'soulful transformation',
  'inner awakening', 'spiritual fulfillment', 'divine insight', 'spiritual reflection', 'sacred journey exploration', 'inner strength journey',
  'spiritual exploration', 'soulful insight', 'inner journey quest', 'spiritual energy', 'sacred vision', 'spiritual commitment',
  'soulful growth', 'spiritual path exploration', 'inner light journey', 'sacred connection', 'spiritual quest for peace',
  'enlightened journey', 'divine awakening', 'spiritual self-discovery', 'soulful reflection', 'inner peace and growth', 'spiritual journey quest',
  'sacred path', 'divine transformation', 'spiritual quest for clarity', 'soulful enlightenment', 'inner peace and balance', 'spiritual commitment journey',
  'sacred practice exploration', 'spiritual development path', 'inner wisdom journey', 'soulful self-discovery', 'spiritual enlightenment quest', 'divine harmony',
  'spiritual journey for growth', 'sacred insight', 'inner peace and serenity', 'spiritual journey for balance', 'soulful understanding', 'divine connection quest',
  'spiritual growth path', 'inner awakening journey', 'sacred quest for peace', 'spiritual renewal journey', 'soulful transformation quest', 'inner journey for insight',
  'spiritual commitment quest', 'divine self-discovery', 'sacred harmony', 'spiritual quest for understanding', 'inner peace exploration', 'soulful balance quest',
  'divine journey', 'spiritual renewal exploration', 'inner growth quest', 'sacred self-discovery', 'spiritual harmony quest', 'soulful enlightenment journey',
  'inner peace quest journey', 'divine spiritual path', 'sacred connection journey', 'spiritual insight journey', 'soulful self-growth', 'inner light quest',
  'spiritual exploration journey', 'sacred transformation', 'inner peace journey quest', 'spiritual commitment exploration', 'soulful renewal', 'divine understanding',
  'spiritual quest for harmony', 'inner peace development', 'sacred growth path', 'soulful insight journey', 'spiritual self-exploration', 'divine journey quest',
  'inner awakening quest', 'sacred enlightenment', 'spiritual connection exploration', 'soulful journey for growth', 'inner peace and connection', 'divine transformation quest',
  'spiritual renewal quest', 'soulful understanding quest', 'inner wisdom exploration', 'spiritual journey for insight', 'sacred journey for balance', 'spiritual growth journey',
  'inner peace exploration quest', 'divine renewal', 'spiritual quest for enlightenment', 'soulful connection journey', 'inner journey for growth', 'spiritual exploration for balance',
  'sacred self-exploration', 'inner peace and growth journey', 'spiritual transformation quest', 'soulful development', 'divine insight journey', 'spiritual awakening exploration',
  'inner peace quest for understanding', 'sacred insight journey', 'spiritual balance exploration', 'soulful journey for peace', 'divine harmony quest', 'spiritual growth quest',
  'inner journey for self-discovery', 'sacred renewal', 'spiritual exploration for insight', 'soulful transformation journey', 'inner peace development quest', 'spiritual quest for renewal',
  'divine connection journey', 'spiritual understanding quest', 'inner light journey quest', 'soulful exploration', 'spiritual harmony development', 'divine self-growth',
  'inner peace journey for insight', 'sacred transformation quest', 'spiritual development journey', 'soulful balance exploration', 'divine quest for enlightenment', 'spiritual awakening journey',
  'inner peace journey development', 'spiritual growth exploration', 'soulful journey for understanding', 'divine path for renewal', 'spiritual self-exploration journey', 'inner peace quest development',
  'sacred balance quest', 'spiritual transformation exploration', 'soulful quest for insight', 'inner wisdom journey quest', 'divine connection exploration', 'spiritual development quest',
  'inner peace and growth exploration', 'sacred self-growth journey', 'spiritual insight development', 'soulful enlightenment journey quest', 'divine understanding exploration', 'inner journey quest development',
  'spiritual growth path exploration', 'soulful journey for connection', 'divine renewal quest', 'inner peace exploration development', 'spiritual understanding journey', 'sacred journey for renewal',
  'spiritual quest for growth', 'soulful transformation exploration', 'inner peace development journey', 'divine insight quest', 'spiritual exploration for harmony', 'soulful development journey',
  'inner peace and enlightenment', 'spiritual journey for self-growth', 'sacred connection exploration', 'spiritual self-discovery quest', 'divine renewal journey', 'inner light exploration',
  'soulful connection quest', 'spiritual quest for balance', 'inner peace and self-discovery', 'sacred exploration for understanding', 'spiritual growth and transformation', 'divine connection journey quest',
  'inner awakening exploration', 'spiritual self-growth journey', 'soulful quest for balance', 'divine understanding development', 'spiritual harmony journey', 'inner peace development quest',
  'sacred journey for self-discovery', 'spiritual exploration for growth', 'soulful insight exploration', 'divine path for understanding', 'inner peace and renewal', 'spiritual journey for balance',
  'sacred connection development', 'spiritual quest for growth and understanding', 'inner wisdom development', 'soulful journey for insight', 'spiritual transformation development', 'divine renewal quest journey',
  'inner peace journey exploration', 'spiritual development and understanding', 'soulful quest for renewal', 'divine connection development', 'spiritual self-discovery development', 'inner peace and growth journey',
  'sacred exploration for balance', 'spiritual growth and understanding', 'soulful connection development', 'inner journey for renewal', 'divine enlightenment quest', 'spiritual harmony exploration',
  'inner peace quest for understanding', 'soulful self-growth journey', 'spiritual path for connection', 'divine self-discovery exploration', 'inner peace and transformation', 'spiritual journey development',
  'soulful insight quest', 'inner peace journey for enlightenment', 'divine renewal development', 'spiritual understanding and growth', 'sacred connection journey exploration', 'inner wisdom quest',
  'spiritual self-exploration and development', 'soulful growth quest', 'divine connection exploration journey', 'inner peace and enlightenment quest', 'spiritual journey for insight', 'sacred growth exploration',
  'soulful journey for understanding', 'inner peace development and growth', 'divine insight journey development', 'spiritual transformation journey quest', 'inner connection exploration', 'soulful development quest',
  'divine self-growth exploration', 'spiritual journey for renewal', 'inner peace quest exploration', 'sacred understanding journey', 'soulful connection and growth', 'divine harmony exploration',
  'spiritual growth development', 'inner peace journey quest development', 'soulful journey for transformation', 'divine insight quest journey', 'spiritual self-discovery exploration', 'inner'
];

// Intellectual category words
const List<String> intellectualWords = [
  'knowledge', 'wisdom', 'learning', 'insight', 'intelligence', 'creativity', 'analysis', 'understanding',
  'critical thinking', 'innovation', 'problem-solving', 'reasoning', 'discovery', 'research', 'enlightenment',
  'strategy', 'conceptualization', 'theory', 'debate', 'exploration', 'cognition', 'reflection', 'knowledge quest',
  'intellectual growth', 'mental challenge', 'academic', 'philosophy', 'inquiry', 'perspective', 'argumentation',
  'brainstorming', 'logic', 'deduction', 'abstraction', 'intuition', 'curiosity', 'study', 'examination', 'scholarship',
  'reflection', 'creative thinking', 'mental acuity', 'analytic thinking', 'innovation challenge', 'strategic planning',
  'philosophical inquiry', 'knowledge expansion', 'research quest', 'concept development', 'problem-solving skills', 'theoretical analysis',
  'critical inquiry', 'scientific method', 'literary analysis', 'intellectual pursuit', 'problem-solving challenge', 'data analysis', 'cognitive skills',
  'academic exploration', 'mental exercises', 'thought experiment', 'strategic thinking', 'academic challenge', 'reasoning skills', 'insight development',
  'creative problem-solving', 'theoretical exploration', 'conceptual challenge', 'academic growth', 'intellectual exploration', 'mental challenge quest',
  'logical reasoning', 'knowledge enhancement', 'analytical skills', 'research challenge', 'philosophical debate', 'strategic exploration', 'problem-solving exercise',
  'mental acuity development', 'scholarly pursuit', 'critical analysis', 'theoretical challenge', 'academic research', 'conceptual thinking', 'data interpretation',
  'cognitive development', 'innovation quest', 'knowledge enrichment', 'philosophical reflection', 'intellectual challenge', 'creative inquiry', 'logical problem-solving',
  'strategic insight', 'mental problem-solving', 'academic exploration quest', 'scientific inquiry', 'literary analysis challenge', 'theoretical development', 'analytical reasoning',
  'knowledge synthesis', 'research and development', 'conceptual exploration', 'problem-solving strategies', 'critical thinking exercise', 'mental growth', 'strategic analysis',
  'scholarly inquiry', 'creative analysis', 'conceptual growth', 'intellectual pursuit challenge', 'data analysis challenge', 'strategic development', 'academic analysis',
  'innovation development', 'philosophical challenge', 'insight exploration', 'intellectual exercises', 'logical analysis', 'mental enrichment', 'theoretical insight',
  'research and inquiry', 'academic growth challenge', 'critical problem-solving', 'knowledge exploration', 'creative challenge', 'strategic thinking exercise', 'scientific exploration',
  'intellectual development', 'analytical challenge', 'conceptual insight', 'mental skills development', 'research insight', 'scholarly development', 'critical thinking challenge',
  'data interpretation challenge', 'philosophical growth', 'intellectual engagement', 'strategic challenge', 'academic enrichment', 'creative thinking challenge', 'problem-solving quest',
  'conceptual problem-solving', 'innovation challenge quest', 'analytical development', 'knowledge exploration challenge', 'theoretical insight development', 'mental challenge exercise',
  'scholarly growth', 'research and innovation', 'creative inquiry challenge', 'philosophical exploration challenge', 'intellectual insights', 'strategic insight development', 'data analysis insight',
  'academic inquiry', 'mental exercise challenge', 'conceptual development challenge', 'logical development', 'philosophical problem-solving', 'scholarly exploration', 'intellectual challenge quest',
  'creative thinking exploration', 'strategic problem-solving', 'data analysis development', 'research challenge quest', 'analytical insight', 'intellectual exploration challenge', 'problem-solving development',
  'mental enrichment challenge', 'academic insight', 'conceptual research', 'philosophical insight', 'intellectual growth quest', 'strategic inquiry', 'creative problem-solving challenge', 'scientific development',
  'intellectual reasoning', 'scholarly challenge', 'research insight development', 'mental skills challenge', 'data analysis development quest', 'conceptual insights', 'innovation insight', 'academic development challenge',
  'philosophical analysis', 'intellectual growth development', 'creative development', 'logical reasoning challenge', 'strategic insight challenge', 'mental exercise development', 'research and development challenge',
  'conceptual growth challenge', 'scholarly insights', 'critical inquiry challenge', 'knowledge development', 'strategic exploration quest', 'analytical problem-solving', 'intellectual engagement challenge',
  'data challenge', 'research and insight', 'philosophical thinking', 'creative insights', 'intellectual journey', 'mental problem-solving challenge', 'academic insight development', 'conceptual growth quest',
  'innovation and creativity', 'strategic challenge quest', 'intellectual challenge development', 'research and development quest', 'creative problem-solving exploration', 'philosophical challenge development',
  'scholarly insight challenge', 'mental growth development', 'analytical development challenge', 'conceptual insights development', 'intellectual enrichment challenge', 'research insight quest', 'strategic inquiry development',
  'data challenge quest', 'scientific challenge', 'creative development challenge', 'philosophical growth challenge', 'intellectual pursuit development', 'academic challenge exploration', 'logical thinking development',
  'mental exercises challenge', 'knowledge enrichment quest', 'strategic development challenge', 'research and development insights', 'analytical growth challenge', 'intellectual challenge exploration', 'creative challenge quest',
  'philosophical inquiry development', 'scholarly challenge quest', 'mental skills growth', 'conceptual analysis development', 'intellectual engagement quest', 'data development challenge', 'research insight exploration',
  'strategic problem-solving challenge', 'creative insights quest', 'philosophical thinking development', 'intellectual growth and development', 'academic pursuit challenge', 'logical development challenge', 'mental challenge growth',
  'knowledge enhancement quest', 'strategic development exploration', 'research and analysis challenge', 'creative development quest', 'scholarly exploration challenge', 'conceptual challenge development', 'philosophical insights quest',
  'intellectual journey quest', 'mental growth exploration', 'academic insights development', 'data analysis challenge quest', 'strategic thinking challenge', 'intellectual pursuit quest', 'creative challenge exploration',
  'philosophical and intellectual challenge', 'scholarly development quest', 'knowledge challenge development', 'analytical insights exploration', 'research development insights', 'conceptual growth exploration',
  'strategic challenge development', 'mental skills development challenge', 'creative insights exploration quest', 'intellectual growth and challenge', 'philosophical research challenge', 'academic insights quest', 'data development insights',
  'strategic exploration challenge', 'research and development quest exploration', 'creative challenge insights', 'intellectual challenge growth', 'scholarly analysis challenge', 'mental challenge and growth', 'conceptual and intellectual insights',
  'academic challenge quest development', 'research and analysis development', 'strategic insights challenge', 'creative problem-solving development', 'philosophical growth insights', 'intellectual journey exploration', 'mental skills growth challenge',
  'knowledge challenge insights', 'strategic development and challenge', 'creative insights development', 'intellectual growth and quest', 'academic development and challenge', 'philosophical and strategic insights', 'data challenge development',
  'scholarly insights and quest', 'mental exercises and challenge', 'conceptual challenge insights', 'intellectual pursuit and growth', 'creative development and exploration', 'research and growth challenge', 'strategic thinking quest',
  'philosophical insights and development', 'academic challenge insights', 'mental growth and challenge quest', 'intellectual development and exploration', 'creative problem-solving insights', 'data development and challenge',
  'scholarly and research quest', 'conceptual growth and challenge', 'strategic insights and development', 'intellectual challenge and growth quest', 'philosophical challenge and insights', 'creative insights and challenge quest',
  'academic and intellectual challenge', 'mental development and growth', 'research and analysis insights', 'intellectual growth challenge', 'philosophical and strategic challenge', 'conceptual development and insights',
  'creative challenge and exploration', 'data analysis and challenge quest', 'scholarly growth and challenge', 'intellectual and mental exercises', 'strategic quest and development', 'academic insights and challenge',
  'creative problem-solving and development', 'intellectual challenge exploration and growth', 'philosophical insights and challenge', 'mental growth challenge quest', 'research and intellectual development' 'data challenge and insights',
];

// Environmental category words
const List<String> environmentalWords = [
  'sustainability', 'recycling', 'conservation', 'eco-friendly', 'green', 'renewable', 'environment', 'wildlife',
  'climate', 'pollution', 'habitat', 'biodiversity', 'nature', 'ecosystem', 'carbon footprint', 'composting',
  'energy efficiency', 'water conservation', 'natural resources', 'earth', 'global warming', 'reforestation',
  'clean energy', 'sustainable living', 'environmental impact', 'waste reduction', 'organic', 'environmentalism',
  'clean water', 'air quality', 'reduce', 'reuse', 'earth-friendly', 'wildlife protection', 'sustainable practices',
  'greenhouse gases', 'conservation efforts', 'climate change', 'nature conservation', 'solar power', 'wind energy',
  'pollution control', 'green technology', 'eco-conscious', 'environmental education', 'sustainable development',
  'energy conservation', 'carbon neutral', 'environmental stewardship', 'eco-system preservation', 'zero waste',
  'green living', 'sustainable agriculture', 'environmental protection', 'organic farming', 'natural habitat',
  'ecological balance', 'energy-saving', 'recycled materials', 'waste management', 'habitat restoration', 'clean air',
  'eco-awareness', 'sustainable resources', 'earth conservation', 'green initiatives', 'climate action',
  'recycling programs', 'renewable energy sources', 'environmental sustainability', 'forest conservation',
  'sustainable practices challenge', 'environmentally friendly', 'conservation projects', 'energy efficiency measures',
  'carbon reduction', 'green spaces', 'pollution reduction', 'natural conservation', 'sustainable living practices',
  'clean energy solutions', 'environmental conservation', 'eco-friendly practices', 'climate solutions', 'biodiversity conservation',
  'water management', 'natural resource conservation', 'waste reduction initiatives', 'sustainable communities',
  'green technology solutions', 'environmental initiatives', 'wildlife conservation efforts', 'recycling initiatives',
  'eco-friendly solutions', 'energy conservation efforts', 'carbon footprint reduction', 'sustainable development practices',
  'environmental responsibility', 'nature preservation', 'green living practices', 'renewable resources',
  'climate protection', 'clean energy projects', 'conservation strategies', 'organic practices', 'eco-friendly initiatives',
  'waste minimization', 'sustainable lifestyle', 'environmental responsibility challenge', 'green energy',
  'water conservation practices', 'earth protection', 'habitat conservation projects', 'carbon offset',
  'sustainable design', 'eco-friendly technology', 'environmental responsibility initiatives', 'recycling efforts',
  'clean technologies', 'renewable energy initiatives', 'nature conservation projects', 'sustainable resource management',
  'biodiversity efforts', 'environmental awareness', 'energy efficiency programs', 'sustainable agriculture practices',
  'green practices', 'climate action initiatives', 'recycling and waste reduction', 'earth-friendly practices',
  'environmental health', 'conservation efforts and projects', 'clean water initiatives', 'eco-friendly lifestyle',
  'renewable energy solutions', 'carbon footprint management', 'sustainable communities initiatives', 'wildlife preservation',
  'environmental action', 'green initiatives challenge', 'climate change mitigation', 'energy-saving measures',
  'sustainable waste management', 'nature protection', 'carbon neutrality', 'environmental advocacy',
  'water conservation strategies', 'green technology innovations', 'sustainable practices and initiatives',
  'conservation and protection', 'eco-friendly solutions challenge', 'waste management strategies', 'sustainable practices challenge',
  'environmental awareness initiatives', 'green projects', 'carbon footprint reduction strategies', 'renewable energy projects',
  'wildlife habitat preservation', 'environmental education programs', 'clean technology solutions', 'recycling strategies',
  'nature conservation efforts', 'green solutions', 'sustainable design practices', 'eco-conscious living',
  'environmental responsibility programs', 'carbon offset initiatives', 'sustainable energy solutions',
  'nature and wildlife conservation', 'clean energy solutions challenge', 'eco-awareness initiatives',
  'environmental sustainability programs', 'biodiversity preservation', 'conservation programs', 'green energy initiatives',
  'climate action projects', 'energy efficiency solutions', 'sustainable lifestyle practices', 'recycling and sustainability',
  'environmental protection measures', 'earth conservation initiatives', 'eco-friendly strategies', 'clean water solutions',
  'sustainable resource use', 'nature protection initiatives', 'environmental conservation programs',
  'green technology development', 'carbon management strategies', 'sustainable agriculture solutions',
  'wildlife protection programs', 'energy conservation solutions', 'clean technology innovations',
  'carbon footprint solutions', 'environmental awareness campaigns', 'green practices and projects',
  'sustainable living strategies', 'nature conservation solutions', 'renewable energy advancements',
  'eco-friendly solutions and projects', 'environmental responsibility campaigns', 'climate change solutions',
  'sustainable design solutions', 'waste reduction and recycling', 'natural resource management', 'clean energy strategies',
  'carbon offset programs', 'sustainable community projects', 'green innovation', 'biodiversity protection initiatives',
  'environmental sustainability solutions', 'eco-friendly development', 'nature and habitat protection',
  'recycling and conservation', 'climate protection measures', 'clean technology advancements',
  'environmental action programs', 'carbon footprint awareness', 'sustainable energy initiatives',
  'green technology projects', 'environmental protection challenges', 'nature conservation strategies',
  'waste management programs', 'recycling and waste initiatives', 'sustainable development solutions',
  'clean energy and technology', 'wildlife habitat protection', 'carbon reduction programs',
  'environmental education and awareness', 'green solutions and practices', 'sustainable resource management strategies',
  'eco-friendly and green initiatives', 'nature preservation efforts', 'recycling and conservation programs',
  'energy efficiency solutions challenge', 'environmental protection initiatives', 'carbon footprint reduction programs',
  'sustainable living solutions', 'clean technology and innovations', 'wildlife protection and conservation',
  'eco-friendly development strategies', 'climate action solutions', 'nature and environmental preservation',
  'renewable energy and sustainability', 'environmental responsibility solutions', 'sustainable design and development',
  'green technology and solutions', 'carbon offset initiatives and programs', 'environmental awareness and education',
  'clean energy advancements and projects', 'sustainable practices and strategies', 'nature conservation and protection',
  'recycling and waste management solutions', 'green energy and technology solutions', 'environmental protection and action',
  'carbon footprint and sustainability initiatives', 'wildlife and nature conservation projects',
  'clean water and environmental solutions', 'sustainable living and development practices', 'environmental education programs and campaigns',
  'eco-friendly and sustainable practices', 'energy conservation and efficiency solutions', 'nature preservation and protection',
  'recycling and sustainability programs', 'green technology and clean energy solutions', 'carbon management and reduction',
  'environmental sustainability and responsibility', 'wildlife habitat and conservation efforts',
  'sustainable resource and waste management', 'environmental action and awareness campaigns', 'clean technology innovations and projects',
  'nature and habitat protection initiatives', 'recycling and environmental conservation', 'sustainable development and living solutions',
  'carbon offset and reduction programs', 'environmental responsibility and protection measures', 'green energy and sustainability',
  'wildlife protection and habitat conservation', 'sustainable practices and initiatives challenge',
  'clean energy solutions and innovations', 'environmental awareness and protection programs', 'nature conservation and sustainability',
  'recycling programs and initiatives', 'carbon footprint reduction and management', 'green technology and clean solutions',
  'energy efficiency and conservation', 'environmental protection and responsibility programs', 'wildlife and nature preservation',
  'sustainable living practices and solutions', 'environmental education and awareness', 'recycling and waste management',
  'sustainable development and technology solutions', 'carbon reduction and offset strategies', 'clean energy and technology advancements'
];

// Financial category words
const List<String> financialWords = [
  'budget', 'savings', 'investment', 'debt', 'income', 'expenses', 'financial planning', 'wealth',
  'retirement', 'savings goals', 'financial independence', 'cash flow', 'financial security', 'portfolio',
  'assets', 'liabilities', 'taxes', 'savings account', 'emergency fund', 'credit score', 'debt reduction',
  'financial growth', 'spending', 'investment strategy', 'financial goals', 'money management', 'wealth building',
  'personal finance', 'expense tracking', 'investment portfolio', 'debt management', 'financial literacy',
  'wealth management', 'financial freedom', 'cash management', 'financial stability', 'retirement savings',
  'financial advice', 'income stream', 'budgeting', 'debt consolidation', 'savings plan', 'financial health',
  'wealth creation', 'investment plan', 'financial strategy', 'credit management', 'money saving', 'tax planning',
  'financial accountability', 'spending plan', 'emergency savings', 'wealth accumulation', 'budget plan',
  'investment opportunities', 'debt reduction plan', 'financial discipline', 'personal budget', 'financial forecast',
  'money goals', 'savings strategy', 'investment growth', 'financial security plan', 'debt elimination',
  'expense management', 'investment analysis', 'financial stability plan', 'wealth protection', 'money allocation',
  'financial reserves', 'personal finance management', 'retirement plan', 'debt-free', 'savings growth',
  'financial well-being', 'investment returns', 'cash reserve', 'budget management', 'financial assessment',
  'spending habits', 'wealth strategy', 'credit repair', 'debt management plan', 'personal wealth', 'savings account management',
  'investment risk', 'financial stability strategy', 'money management plan', 'wealth preservation', 'financial tracking',
  'budgeting plan', 'investment diversification', 'debt recovery', 'financial resources', 'personal financial goals',
  'cash flow management', 'financial wellness', 'savings allocation', 'retirement account', 'debt repayment',
  'financial analysis', 'investment choices', 'money allocation plan', 'financial security strategy', 'wealth goals',
  'budget allocation', 'investment growth strategy', 'personal finance plan', 'financial health check', 'money-saving habits',
  'wealth building strategies', 'savings goals plan', 'financial management plan', 'cash savings', 'debt settlement',
  'investment potential', 'budget review', 'financial planning strategies', 'wealth accumulation plan', 'money control',
  'financial strategies', 'investment review', 'debt management strategies', 'personal financial assessment',
  'emergency fund planning', 'wealth creation plan', 'savings goals strategy', 'financial performance', 'money management strategies',
  'budgeting tools', 'investment opportunities plan', 'debt reduction strategies', 'financial position', 'wealth management plan',
  'savings growth plan', 'retirement fund', 'financial milestones', 'money-saving strategies', 'financial management tools',
  'investment planning', 'debt handling', 'personal savings', 'financial goal setting', 'wealth optimization',
  'budget tracking', 'investment management', 'financial position review', 'money management techniques',
  'savings plan development', 'retirement planning strategies', 'debt relief', 'financial assessments and planning',
  'wealth creation strategies', 'investment options', 'budgeting techniques', 'financial management strategies',
  'money management skills', 'savings review', 'investment risk management', 'personal budget management',
  'financial planning and analysis', 'wealth-building plan', 'savings and investment', 'budgeting and tracking',
  'financial resilience', 'debt payoff plan', 'retirement savings strategy', 'money-saving techniques',
  'financial planning tools', 'investment growth review', 'wealth protection strategies', 'financial planning and strategy',
  'personal finance strategies', 'savings and goals', 'investment decisions', 'debt reduction goals', 'financial stability tools',
  'budget planning strategies', 'wealth growth', 'financial responsibility', 'investment returns planning', 'personal savings plan',
  'financial stability and growth', 'retirement planning tools', 'budgeting and financial planning', 'investment planning and review',
  'debt management and repayment', 'financial goals and strategies', 'money-saving plan', 'savings and investment strategies',
  'wealth accumulation tools', 'financial planning goals', 'investment risk assessment', 'debt management and elimination',
  'retirement fund management', 'financial health tools', 'money management review', 'budgeting and savings plans',
  'financial management and tracking', 'investment opportunities review', 'personal financial management strategies',
  'wealth management tools', 'savings goals review', 'financial performance assessment', 'retirement savings plan',
  'investment growth and planning', 'budget allocation strategies', 'debt repayment plan', 'financial resilience strategies',
  'money management tools', 'wealth-building goals', 'financial tracking tools', 'investment review and strategy',
  'budget and savings strategies', 'retirement planning and goals', 'debt settlement plan', 'financial health and planning',
  'money-saving goals', 'wealth management strategies', 'investment and savings planning', 'financial assessment tools',
  'budget and financial goals', 'retirement planning review', 'personal finance management tools', 'financial tracking and planning',
  'investment strategy development', 'savings review and goals', 'debt management review', 'financial strategy and planning',
  'wealth accumulation and management', 'budgeting goals and strategies', 'financial planning tools and techniques',
  'investment management and growth', 'savings and financial goals', 'personal financial goals review',
  'retirement and savings strategies', 'debt repayment and management', 'financial resilience planning',
  'wealth-building and management', 'investment review and planning', 'budgeting and financial management',
  'financial health and resilience', 'savings goals and strategies', 'retirement planning and review',
  'financial planning and tracking', 'investment opportunities and planning', 'money management and savings',
  'wealth management and growth', 'personal financial management review', 'budget and financial performance',
  'retirement savings review', 'investment growth and goals', 'financial strategy and tools', 'debt management and strategy',
  'financial performance and planning', 'wealth-building and strategies', 'savings and investment review',
  'financial tracking and management', 'retirement planning goals and strategies', 'investment planning and growth',
  'personal finance tools and strategies', 'financial assessment and planning', 'wealth management review',
  'budgeting and financial management tools', 'retirement and savings management', 'debt repayment and goals',
  'financial health and growth', 'investment and financial strategies', 'money management goals and plans',
  'wealth-building and planning', 'savings and financial performance', 'retirement planning review and strategies',
  'financial planning and goals', 'investment management and review', 'budgeting and savings review',
  'financial resilience and strategy', 'personal finance management and tools', 'retirement and financial goals',
  'wealth accumulation and strategies', 'financial performance review and planning', 'investment and savings planning',
  'financial tracking tools and strategies', 'debt management and financial planning', 'wealth-building tools',
  'personal financial management strategies', 'budgeting and investment review', 'financial growth and management',
  'retirement planning and financial tools', 'investment review and goals', 'money management and growth',
  'financial planning and strategies review', 'wealth management and growth tools', 'savings review and performance',
  'retirement and financial performance', 'investment and financial goals review', 'budgeting and financial planning tools'
];